name: Git_Final
on:
  push:
    branches:
        - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:

      - name: print hello
        run: echo "Hello"

      - name: ubuntu version
        run: lsb_release -a

      - name: print sha
        run: |
          echo $GITHUB_SHA
          

  job-2:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4

       - name: run file
         run: |
           chmod +x test.sh
           ./test.sh

  job-3:
    runs-on: ubuntu-latest
    steps:
       - name: print  name
         env:
           PHONE_NUM: ${{ secrets.PHONE_NUM }}
         run: |
           echo "Phone Number: $(echo $PHONE_NUM | base64 -d)"  
           echo "First Name: ${{ env.FIRST_NAME }}"
           x="Eropa"
           echo "Last Name: $x"
           

       
         




       
